/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgres://username:password@localhost:5432/estudos -t users -s public
 *
 */


export type Json = unknown;

// Table users
export interface Users {
  id: number;
  name: string;
  email: string;
  date_birth: Date | null;
  created_at: Date | null;
  updated_at: Date | null;
}
export interface UsersInput {
  id?: number;
  name: string;
  email: string;
  date_birth?: Date | null;
  created_at?: Date | null;
  updated_at?: Date | null;
}
const users = {
  tableName: 'users',
  columns: ['id', 'name', 'email', 'date_birth', 'created_at', 'updated_at'],
  requiredForInsert: ['name', 'email'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Users,
  $input: null as unknown as UsersInput
} as const;


export interface TableTypes {
  users: {
    select: Users;
    input: UsersInput;
  };
}

export const tables = {
  users,
}
